In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)
print(b)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [4]:
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

print("number of dimensions of a:", a.ndim)
print("number of dimensions of b:", b.ndim)

Shape of a: (5,)
Shape of b: (2, 3)
number of dimensions of a: 1
number of dimensions of b: 2


In [7]:
X = np.array([1, 2, 3, 4, 5])

print("X shape before:", X.shape)

X = X.reshape(-1, 1)
print("X shape after reshape:", X.shape)


X shape before: (5,)
X shape after reshape: (5, 1)


In [8]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

print(x + y)
print(x * y)
print(x ** 2)


[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]


In [9]:
data = np.array([12, 15, 20, 22, 25, 30])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std Dev:", np.std(data))


Mean: 20.666666666666668
Median: 21.0
Std Dev: 5.9907335852038095


In [10]:
X = np.array([100, 120, 140, 160, 180]).reshape(-1, 1)
y = np.array([200, 240, 280, 320, 360])

print(X)
print(y)


[[100]
 [120]
 [140]
 [160]
 [180]]
[200 240 280 320 360]


In [21]:
X = np.array([5,10,15,20,25,30,35,40,45,50])

print("elements:", X)

new_shape = X.reshape(10, 1)
print("reshaped elements:", new_shape)

print("Mean:", np.mean(new_shape))
print("Median:", np.median(new_shape))
print("Std Dev:", np.std(new_shape))
print("Max:", np.max(new_shape))
print("Min:", np.min(new_shape))
print("square:", np.square(new_shape))

elements: [ 5 10 15 20 25 30 35 40 45 50]
reshaped elements: [[ 5]
 [10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]
 [50]]
Mean: 27.5
Median: 27.5
Std Dev: 14.361406616345072
Max: 50
Min: 5
square: [[  25]
 [ 100]
 [ 225]
 [ 400]
 [ 625]
 [ 900]
 [1225]
 [1600]
 [2025]
 [2500]]
